---
title: "Microscopic Findings (MI) domain"
output: html_document
date: Sep-10-2024
author: Md Yousuf Ali
toc: false
---



```{r}
#| include=FALSE
library(DT)
library(data.table)
```



```{r}
#| include=FALSE
path <- '~/OneDrive - FDA/yousuf/00_github_projects/SENDsanitizer/'
file_org <- 'no_git_dir/code/phuse/PDS/mi.xpt'
file_fake  <- 'no_git_dir/code/phuse/FAKE15218/mi.xpt'
```



```{r}
#| include=FALSE
mi_org <- haven::read_xpt(fs::path(path,file_org))
```

##  Original Data


```{r}
#| echo=FALSE
mi_org <- as.data.frame(mi_org)
DT::datatable(mi_org,options = list(pageLength = 10))
colnames(mi_org)
```

##  Columns that changed in original (red background)

```{r}
#| echo=FALSE
DT::datatable(mi_org,options = list(pageLength=10)) |>
  DT::formatStyle(columns = c('STUDYID','USUBJID','MIORRES','MISTRESC',
                             'MISEV', 'MIDTC'),
                  backgroundColor = '#fbcccf')
```



```{r}
#| include=FALSE
mi_fake <- haven::read_xpt(fs::path(path,file_fake))
```

## Synthetic Data


```{r}
#| echo=FALSE
mi_fake <- as.data.frame(mi_fake)
data.table::setDT(mi_fake)
colnames(mi_fake)
data.table::setcolorder(mi_fake,'USUBJID', after = 'DOMAIN')
DT::datatable(mi_fake,options = list(pageLength = 10))
```

## Synthetic Data with columns that changed (blue background)

```{r}
#| echo=FALSE
DT::datatable(mi_fake,options = list(pageLength=10)) |>
  DT::formatStyle(columns = c('STUDYID','USUBJID','MIORRES',
                              'MISTRESC','MISEV','MIDTC'),
                          backgroundColor = 'skyblue')
```



```{r}
#| include=FALSE
data.table::setDT(mi_org)
data.table::setDT(mi_fake)
```
```{r}
#| include=FALSE
mi_merge <- merge(mi_org,mi_fake[,.(STUDYID,USUBJID,
                                    MISEQ,MISTRESC,MIORRES,MISEV,MIDTC)],
                  by = c('MISEQ'),suffixes = c('_original','_fake'))
data.table::setcolorder(mi_merge,
                        c("STUDYID_original", "STUDYID_fake", "DOMAIN",
                          "USUBJID_original","USUBJID_fake",
                          "MIORRES_original","MIORRES_fake",
                          "MISTRESC_original", "MISTRESC_fake",
                          "MISEV_original","MISEV_fake",
                          "MIDTC_original","MIDTC_fake", "MIDY"
                          ))
DT::datatable(mi_merge, options = list(pageLength=20)) |>
  DT::formatStyle(grep('fake',colnames(mi_merge),value = T),
                  backgroundColor = 'skyblue') |>
  DT::formatStyle(grep('original',colnames(mi_merge),value = T),
                  backgroundColor = '#fbcccf')
```

