---
title: "Organ Measurements (OM) Domain"
output: html_document
date: Sep-10-2024
author: Md Yousuf Ali
toc: false
---



```{r}
#| include=FALSE
library(DT)
library(data.table)
```



```{r}
#| include=FALSE
path <- '~/OneDrive - FDA/yousuf/00_github_projects/SENDsanitizer/'
file_org <- 'no_git_dir/code/phuse/PDS/om.xpt'
file_fake  <- 'no_git_dir/code/phuse/FAKE15218/om.xpt'
```



```{r}
#| include=FALSE
om_org <- haven::read_xpt(fs::path(path,file_org))
```

##  Original Data


```{r}
#| echo=FALSE
om_org <- as.data.frame(om_org)
DT::datatable(om_org,options = list(pageLength = 10))
colnames(om_org)
```

## Columns that changed in original data (red background)

```{r}
#| echo=FALSE
DT::datatable(om_org,options = list(pageLength=10)) |>
  DT::formatStyle(columns = c('STUDYID','USUBJID','OMORRES','OMSTRESC',
                              'OMSTRESN','OMDTC'),
                  backgroundColor = '#fbcccf')
```



```{r}
#| include=FALSE
om_fake <- haven::read_xpt(fs::path(path,file_fake))
```

## Synthetic data


```{r}
#| echo=FALSE
om_fake <- as.data.frame(om_fake)
data.table::setDT(om_fake)
data.table::setcolorder(om_fake,'USUBJID', after = 'DOMAIN')
DT::datatable(om_fake,options = list(pageLength = 10))
```

## Synthetic Data with columns that changed (blue bakcground)

```{r}
#| echo=FALSE
DT::datatable(om_fake,options = list(pageLength=10)) |>
  DT::formatStyle(columns = c('STUDYID','USUBJID','OMORRES',
                              'OMSTRESC','OMSTRESN','OMDTC'),
                          backgroundColor = 'skyblue')
```



```{r}
#| include=FALSE
data.table::setDT(om_org)
data.table::setDT(om_fake)
```
```{r}
#| include=FALSE
om_merge <- merge(om_org,om_fake[,.(STUDYID,USUBJID,OMSTRESN,
                                    OMSEQ,OMSTRESC,OMORRES,OMDTC)],
                  by = c('OMSEQ'),suffixes = c('_original','_fake'))

data.table::setcolorder(om_merge,
                        c("STUDYID_original", "STUDYID_fake", "DOMAIN",
                          "USUBJID_original","USUBJID_fake",
                          "OMORRES_original","OMORRES_fake", "OMORRESU",
                          "OMSTRESC_original", "OMSTRESC_fake",
                          "OMSTRESN_original", "OMSTRESN_fake",
                          "OMDTC_original","OMDTC_fake", "OMDY"
                          ))
DT::datatable(om_merge, options = list(pageLength=20)) |>
  DT::formatStyle(grep('fake',colnames(om_merge),value = T),
                  backgroundColor = 'skyblue') |>
  DT::formatStyle(grep('original',colnames(om_merge),value = T),
                  backgroundColor = '#fbcccf')
```

