---
title: "Trial Summary (TS) Domain"
output: html_document
date: Sep-08-2024
author: Md Yousuf Ali
toc: false
---



```{r}
#| include=FALSE
library(DT)
library(data.table)
```



```{r}
#| include=FALSE
path <- '~/OneDrive - FDA/yousuf/00_github_projects/SENDsanitizer/'
file_org <- 'no_git_dir/code/phuse/PDS/ts.xpt'
file_fake  <- 'no_git_dir/code/phuse/FAKE15218/ts.xpt'
```



```{r}
#| include=FALSE
ts_org <- haven::read_xpt(fs::path(path,file_org))
```

##  original data


```{r}
#| echo=FALSE
ts_org <- as.data.frame(ts_org)
DT::datatable(ts_org,options = list(pageLength = -1))
```



```{r}
#| include=FALSE
ts_fake <- haven::read_xpt(fs::path(path,file_fake))
```

## fake data


```{r}
#| echo=FALSE
ts_fake <- as.data.frame(ts_fake)
DT::datatable(ts_fake,options = list(pageLength = -1))
```

## print which data changes

```{r}
#| echo=FALSE
DT::datatable(ts_fake,options = list(pageLength = -1)) |>
  DT::formatStyle('STUDYID',
                  backgroundColor = 'skyblue') |>
  formatStyle('TSVAL', valueColumns = 'TSPARMCD',
              backgroundColor = styleEqual(c(c('TRT','TRTV','TRTCAS',
                                               'TSTFLOC','TSTFNAM',
                                               'EXPENDTC','EXPSTDTC','STITLE',
                                               'STSTDTC',
                                               'SPLRNAM','TFCNTRY','SSPONSOR',
                                               'SPREFID','STDIR','TRMSAC'
                                               )), c('skyblue'))) |>
  formatStyle('TSPARMCD',
               color = styleEqual(
                 c('TRT','TRTV','TRTCAS','TSTFLOC','TSTFNAM',
                   'EXPENDTC','EXPSTDTC','STITLE','STSTDTC',
                   'SPLRNAM','TFCNTRY','SSPONSOR',
                   'SPREFID','STDIR','TRMSAC'), c('red')))
```



```{r}
#| include=FALSE
ll <- merge(ts_org,ts_fake[,c('STUDYID','TSSEQ','TSVAL','TSPARMCD')],
            by = c('TSPARMCD','TSSEQ'),
            suffixes = c('_original','_fake'))
data.table::setDT(ll)
data.table::setcolorder(ll, c('STUDYID_original','STUDYID_fake',
                              'DOMAIN','TSSEQ','TSGRPID','TSPARMCD',
                              'TSPARM','TSVAL_original','TSVAL_fake'))
```

##  now side by side comparison

```{r}
#| echo=FALSE
DT::datatable(ll, options = list(pageLength = -1)) |>
  DT::formatStyle('STUDYID_fake',
                  backgroundColor = 'skyblue') |>
  formatStyle('TSVAL_fake', valueColumns = 'TSPARMCD',
              backgroundColor = styleEqual(c(c('TRT','TRTV','TRTCAS',
                                               'TSTFLOC','TSTFNAM',
                                               'EXPENDTC','EXPSTDTC','STITLE',
                                               'STSTDTC',
                                               'SPLRNAM','TFCNTRY','SSPONSOR',
                                               'SPREFID','STDIR','TRMSAC'
                                               )), c('skyblue'))) |>
  formatStyle('TSPARMCD',
              color = styleEqual(
                c('TRT','TRTV','TRTCAS','TSTFLOC','TSTFNAM',
                  'EXPENDTC','EXPSTDTC','STITLE','STSTDTC',
                  'SPLRNAM','TFCNTRY','SSPONSOR',
                  'SPREFID','STDIR','TRMSAC'), c('red')))
```

