
.onLoad <- function(libname, pkgname) { # nolint

    # make data set names global to avoid CHECK notes

utils::globalVariables('setProgress')
utils::globalVariables('ExampleStudy1')
utils::globalVariables('USUBJID')
utils::globalVariables('runif')
utils::globalVariables('DSDECOD')
utils::globalVariables('VISITDY')
utils::globalVariables('BWTESTCD')
utils::globalVariables('BWDY')
utils::globalVariables('SEX')
utils::globalVariables('BWSTRESN')
utils::globalVariables('sd')
utils::globalVariables('rnorm')
utils::globalVariables('ggplot')
utils::globalVariables('aes')
utils::globalVariables('geom_line')
utils::globalVariables('ARMavg')
utils::globalVariables('ggtitle')
utils::globalVariables('labs')
utils::globalVariables('scale_color_manual')
utils::globalVariables('LBTESTCD')
utils::globalVariables('LBDY')
utils::globalVariables('LBSTRESN')
utils::globalVariables('na.omit')
utils::globalVariables('reshape')
utils::globalVariables('as.formula')
utils::globalVariables('tail')
utils::globalVariables('geom_point')
utils::globalVariables('scale_x_discrete')
utils::globalVariables('nls')
utils::globalVariables('predict')
utils::globalVariables('LBSTRESN.SPGRAV')
utils::globalVariables('LBSTRESN.VOLUME')
utils::globalVariables('ARM')
utils::globalVariables('x')
utils::globalVariables('y')
utils::globalVariables('MISPEC')
utils::globalVariables('MISTRESC')
utils::globalVariables('MISEV')
  invisible()
}
